//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1234
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeView
    {
        public int C_ { get; set; }
        public string Сотрудник { get; set; }
        public string Телефон { get; set; }
        public string Email { get; set; }
    }
}
