//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1234
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsView
    {
        public int C_ { get; set; }
        public string Наименование { get; set; }
        public Nullable<int> Кол_во { get; set; }
        public Nullable<int> Цена { get; set; }
        public string Дата { get; set; }
        public Nullable<int> Срок { get; set; }
        public string Дата_списания { get; set; }
        public string Ответственный { get; set; }
        public string Категория { get; set; }
    }
}
