//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1234
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public int ID_item { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> Ammount { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> LifeTime { get; set; }
        public string BuyDate { get; set; }
        public string OffDate { get; set; }
        public Nullable<int> FK_ResponsibleEmployee { get; set; }
        public Nullable<int> FK_Category { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
